In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {"agents":["ninja","beast","dragon","nerd"],'ranks':[50,60,70,80],'cost':[10,20,30,40]}
df = pd.DataFrame(data)
print(df)

   agents  ranks  cost
0   ninja     50    10
1   beast     60    20
2  dragon     70    30
3    nerd     80    40


In [3]:
print(df[['agents','cost']])

   agents  cost
0   ninja    10
1   beast    20
2  dragon    30
3    nerd    40


In [4]:
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [5]:
arr2 = np.array([[1,2,3,4],[11,22,33,44]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
arr2.sum(1)

[[ 1  2  3  4]
 [11 22 33 44]]
<class 'numpy.ndarray'>
2


array([ 10, 110])

In [6]:
arr2[:]

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [7]:
arr2[:,3]

array([ 4, 44])

In [8]:
arr3 = np.array([[[33,55,77,99]]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
arr3.sum(2)
arr3.max(2)

[[[33 55 77 99]]]
<class 'numpy.ndarray'>
3


array([[99]])

In [9]:
df

agents  ranks  cost
0   ninja     50    10
1   beast     60    20
2  dragon     70    30
3    nerd     80    40

In [10]:
first = df.loc[0]
second = df.loc[3]
print(first,"\n\n\n",second)

agents    ninja
ranks        50
cost         10
Name: 0, dtype: object 


 agents    nerd
ranks       80
cost        40
Name: 3, dtype: object


In [11]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
df1 = pd.DataFrame(dict)
df1.notnull()

First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [12]:
df1.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [13]:
df1.fillna('filled')

First Score Second Score Third Score
0         100           30      filled
1          90           45          40
2      filled           56          80
3          95       filled          98