In [1]:
import numpy as np

arr1 = np.array([[[1,2,3,4,5],[1,2,3,4,6]],[[0,9,8,7,7],[7,6,5,4,3]]])
print(arr1)
print(type(arr1))
print(arr1.ndim)
print("\n")
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,6]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print("\n")
arr3 = np.array([1,2,3,4,5])
print(arr3)
print(type(arr3))
print(arr3.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 6]]

 [[0 9 8 7 7]
  [7 6 5 4 3]]]
<class 'numpy.ndarray'>
3


[[1 2 3 4 5]
 [1 2 3 4 6]]
<class 'numpy.ndarray'>
2


[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [3]:
arr1_zero = np.zeros((3,3), dtype=float)
print(arr1_zero)
print("\n")
arr2_zero = np.zeros((3,2),dtype=bool)
print(arr2_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[False False]
 [False False]
 [False False]]


In [5]:
arr_range = np.arange(1,20,3, dtype=int)
print(arr_range)

[ 1  4  7 10 13 16 19]


In [6]:
data = np.array([['','Col1','Col2'],['Row1',1,2],['Row2',3,4]])
print(data)
print(data[0][1])

#retrieves 3rd column from all rows
data[:,2]

[['' 'Col1' 'Col2']
 ['Row1' '1' '2']
 ['Row2' '3' '4']]
Col1


array(['Col2', '2', '4'], dtype='<U4')

In [8]:
#converting list,tuples and dictionaries to numpy array

list1 = ["paris","NY","Dehli","India"]
print(type(list1),end=",")
tuple1 = ('dog','cat','bat')
print(type(tuple1),end=",")
dictionary = {0:'yashvi',1:'heli',2:'dhara'}
print(type(dictionary),'\n')
print('-------------------------------------------------------------\n')
arr3 = np.array(list1)
print(arr3,type(arr3),'\n')
arr4 = np.array(tuple1)
print(arr4,type(arr4),'\n')
arr5 = np.array(dictionary)
print(arr5,type(arr5),'\n')
print('This is 0 dimensional array. Hence not useful--> dimension of arr5 = ',arr5.ndim)

<class 'list'>,<class 'tuple'>,<class 'dict'> 

-------------------------------------------------------------

['paris' 'NY' 'Dehli' 'India'] <class 'numpy.ndarray'> 

['dog' 'cat' 'bat'] <class 'numpy.ndarray'> 

{0: 'yashvi', 1: 'heli', 2: 'dhara'} <class 'numpy.ndarray'> 

This is 0 dimensional array. Hence not useful--> dimension of arr5 =  0


In [9]:
#reshaping 1d array (i.e. tuple1 to 1d array) to 2d array
arr4_2d = arr4.reshape(3,1)
print(arr4_2d,'\n','dimension of arr4 after reshaping is :',arr4_2d.ndim)
arr4_2d[:,0]
print(arr4_2d[0][0],'&',arr4_2d[1][0],'&',arr4_2d[2][0])

#dictionary to numpy array

result = dictionary.items()
data = list(result)
ndarray=np.array(data)

print('\ndict to array is :\n',ndarray)
print('\n',ndarray.ndim)
print('\n',type(ndarray))
print('\n',type(dictionary))

[['dog']
 ['cat']
 ['bat']] 
 dimension of arr4 after reshaping is : 2
dog & cat & bat

dict to array is :
 [['0' 'yashvi']
 ['1' 'heli']
 ['2' 'dhara']]

 2

 <class 'numpy.ndarray'>

 <class 'dict'>


In [11]:
import pandas as pd
#creating dataframe from various data types

#from dictionary
data = {"agents":["ninja","beast","dragon","nerd"],'ranks':[50,60,70,80],'cost':[10,20,30,40]}
df3 = pd.DataFrame(data)
df3

agents  ranks  cost
0   ninja     50    10
1   beast     60    20
2  dragon     70    30
3    nerd     80    40

In [12]:
#from list data-type
ls1 = ['jan','feb','march','april','may','june']
df1 = pd.DataFrame(ls1,columns=['months'])
df1

months
0    jan
1    feb
2  march
3  april
4    may
5   june

In [13]:
#from tuples

tup = ('mon','tue','wed','thu')
df2 = pd.DataFrame(tup,columns=['days'])
df2

days
0  mon
1  tue
2  wed
3  thu

In [14]:
#from numpy array
num_arr = np.array([[2,4],
                    [4,16],
                    [8,64]])

df4 = pd.DataFrame(num_arr,columns=['num','square'])
df4['square_of_square'] = df4['square']**2
df4

num  square  square_of_square
0    2       4                16
1    4      16               256
2    8      64              4096